export const perfis = ["Administrador", "Back Office", "Técnico"];

export const mockUsuarios = [
  {
    id: 1,
    nome: "Ana Silva",
    email: "ana.silva@empresa.com",
    departamento: "Recursos Humanos",
    ativo: true,
    dataCadastro: "15/01/2024",
  },
  {
    id: 2,
    nome: "Carlos Oliveira",
    email: "carlos.oliveira@empresa.com",
    departamento: "Tecnologia",
    ativo: true,
    dataCadastro: "16/01/2024",
  },
  {
    id: 3,
    nome: "Mariana Santos",
    email: "mariana.santos@empresa.com",
    departamento: "Financeiro",
    ativo: true,
    dataCadastro: "17/01/2024",
  },
  {
    id: 4,
    nome: "João Pereira",
    email: "joao.pereira@empresa.com",
    departamento: "Marketing",
    ativo: false,
    dataCadastro: "18/01/2024",
  },
  {
    id: 5,
    nome: "Fernanda Lima",
    email: "fernanda.lima@empresa.com",
    departamento: "Vendas",
    ativo: true,
    dataCadastro: "19/01/2024",
  },
  {
    id: 6,
    nome: "Ricardo Almeida",
    email: "ricardo.almeida@empresa.com",
    departamento: "Operações",
    ativo: true,
    dataCadastro: "20/01/2024",
  },
  {
    id: 7,
    nome: "Juliana Costa",
    email: "juliana.costa@empresa.com",
    departamento: "Recursos Humanos",
    ativo: true,
    dataCadastro: "21/01/2024",
  },
  {
    id: 8,
    nome: "Pedro Henrique",
    email: "pedro.henrique@empresa.com",
    departamento: "Tecnologia",
    ativo: false,
    dataCadastro: "22/01/2024",
  },
  {
    id: 9,
    nome: "Amanda Rodrigues",
    email: "amanda.rodrigues@empresa.com",
    departamento: "Financeiro",
    ativo: true,
    dataCadastro: "23/01/2024",
  },
  {
    id: 10,
    nome: "Bruno Carvalho",
    email: "bruno.carvalho@empresa.com",
    departamento: "Marketing",
    ativo: true,
    dataCadastro: "24/01/2024",
  },
  {
    id: 11,
    nome: "Patrícia Nunes",
    email: "patricia.nunes@empresa.com",
    departamento: "Vendas",
    ativo: true,
    dataCadastro: "25/01/2024",
  },
  {
    id: 12,
    nome: "Lucas Martins",
    email: "lucas.martins@empresa.com",
    departamento: "Operações",
    ativo: false,
    dataCadastro: "26/01/2024",
  },
  {
    id: 13,
    nome: "Camila Ferreira",
    email: "camila.ferreira@empresa.com",
    departamento: "Recursos Humanos",
    ativo: true,
    dataCadastro: "27/01/2024",
  },
  {
    id: 14,
    nome: "Rafael Souza",
    email: "rafael.souza@empresa.com",
    departamento: "Tecnologia",
    ativo: true,
    dataCadastro: "28/01/2024",
  },
  {
    id: 15,
    nome: "Isabela Rocha",
    email: "isabela.rocha@empresa.com",
    departamento: "Financeiro",
    ativo: true,
    dataCadastro: "29/01/2024",
  },
  {
    id: 16,
    nome: "Diego Alves",
    email: "diego.alves@empresa.com",
    departamento: "Marketing",
    ativo: false,
    dataCadastro: "30/01/2024",
  },
  {
    id: 17,
    nome: "Laura Mendes",
    email: "laura.mendes@empresa.com",
    departamento: "Vendas",
    ativo: true,
    dataCadastro: "31/01/2024",
  },
  {
    id: 18,
    nome: "Thiago Barbosa",
    email: "thiago.barbosa@empresa.com",
    departamento: "Operações",
    ativo: true,
    dataCadastro: "01/02/2024",
  },
  {
    id: 19,
    nome: "Vanessa Lima",
    email: "vanessa.lima@empresa.com",
    departamento: "Recursos Humanos",
    ativo: true,
    dataCadastro: "02/02/2024",
  },
  {
    id: 20,
    nome: "Gustavo Silva",
    email: "gustavo.silva@empresa.com",
    departamento: "Tecnologia",
    ativo: false,
    dataCadastro: "03/02/2024",
  },
  {
    id: 21,
    nome: "Daniela Costa",
    email: "daniela.costa@empresa.com",
    departamento: "Financeiro",
    ativo: true,
    dataCadastro: "04/02/2024",
  },
  {
    id: 22,
    nome: "Marcos Oliveira",
    email: "marcos.oliveira@empresa.com",
    departamento: "Marketing",
    ativo: true,
    dataCadastro: "05/02/2024",
  },
  {
    id: 23,
    nome: "Beatriz Santos",
    email: "beatriz.santos@empresa.com",
    departamento: "Vendas",
    ativo: true,
    dataCadastro: "06/02/2024",
  },
  {
    id: 24,
    nome: "André Pereira",
    email: "andre.pereira@empresa.com",
    departamento: "Operações",
    ativo: false,
    dataCadastro: "07/02/2024",
  },
  {
    id: 25,
    nome: "Sofia Almeida",
    email: "sofia.almeida@empresa.com",
    departamento: "Recursos Humanos",
    ativo: true,
    dataCadastro: "08/02/2024",
  },
  {
    id: 26,
    nome: "Roberto Lima",
    email: "roberto.lima@empresa.com",
    departamento: "Tecnologia",
    ativo: true,
    dataCadastro: "09/02/2024",
  },
  {
    id: 27,
    nome: "Tatiane Rodrigues",
    email: "tatiane.rodrigues@empresa.com",
    departamento: "Financeiro",
    ativo: true,
    dataCadastro: "10/02/2024",
  },
  {
    id: 28,
    nome: "Felipe Carvalho",
    email: "felipe.carvalho@empresa.com",
    departamento: "Marketing",
    ativo: false,
    dataCadastro: "11/02/2024",
  },
  {
    id: 29,
    nome: "Cristina Nunes",
    email: "cristina.nunes@empresa.com",
    departamento: "Vendas",
    ativo: true,
    dataCadastro: "12/02/2024",
  },
  {
    id: 30,
    nome: "Leonardo Martins",
    email: "leonardo.martins@empresa.com",
    departamento: "Operações",
    ativo: true,
    dataCadastro: "13/02/2024",
  },
  {
    id: 31,
    nome: "Renata Ferreira",
    email: "renata.ferreira@empresa.com",
    departamento: "Recursos Humanos",
    ativo: true,
    dataCadastro: "14/02/2024",
  },
  {
    id: 32,
    nome: "Eduardo Souza",
    email: "eduardo.souza@empresa.com",
    departamento: "Tecnologia",
    ativo: false,
    dataCadastro: "15/02/2024",
  },
  {
    id: 33,
    nome: "Gabriela Rocha",
    email: "gabriela.rocha@empresa.com",
    departamento: "Financeiro",
    ativo: true,
    dataCadastro: "16/02/2024",
  },
  {
    id: 34,
    nome: "Rodrigo Alves",
    email: "rodrigo.alves@empresa.com",
    departamento: "Marketing",
    ativo: true,
    dataCadastro: "17/02/2024",
  },
  {
    id: 35,
    nome: "Larissa Mendes",
    email: "larissa.mendes@empresa.com",
    departamento: "Vendas",
    ativo: true,
    dataCadastro: "18/02/2024",
  },
  {
    id: 36,
    nome: "Alexandre Barbosa",
    email: "alexandre.barbosa@empresa.com",
    departamento: "Operações",
    ativo: false,
    dataCadastro: "19/02/2024",
  },
  {
    id: 37,
    nome: "Priscila Lima",
    email: "priscila.lima@empresa.com",
    departamento: "Recursos Humanos",
    ativo: true,
    dataCadastro: "20/02/2024",
  },
  {
    id: 38,
    nome: "Vinícius Silva",
    email: "vinicius.silva@empresa.com",
    departamento: "Tecnologia",
    ativo: true,
    dataCadastro: "21/02/2024",
  },
  {
    id: 39,
    nome: "Natália Costa",
    email: "natalia.costa@empresa.com",
    departamento: "Financeiro",
    ativo: true,
    dataCadastro: "22/02/2024",
  },
  {
    id: 40,
    nome: "Maurício Oliveira",
    email: "mauricio.oliveira@empresa.com",
    departamento: "Marketing",
    ativo: false,
    dataCadastro: "23/02/2024",
  },
  {
    id: 41,
    nome: "Helena Santos",
    email: "helena.santos@empresa.com",
    departamento: "Vendas",
    ativo: true,
    dataCadastro: "24/02/2024",
  },
  {
    id: 42,
    nome: "Samuel Pereira",
    email: "samuel.pereira@empresa.com",
    departamento: "Operações",
    ativo: true,
    dataCadastro: "25/02/2024",
  },
  {
    id: 43,
    nome: "Yasmin Almeida",
    email: "yasmin.almeida@empresa.com",
    departamento: "Recursos Humanos",
    ativo: true,
    dataCadastro: "26/02/2024",
  },
  {
    id: 44,
    nome: "Paulo Lima",
    email: "paulo.lima@empresa.com",
    departamento: "Tecnologia",
    ativo: false,
    dataCadastro: "27/02/2024",
  },
  {
    id: 45,
    nome: "Carolina Rodrigues",
    email: "carolina.rodrigues@empresa.com",
    departamento: "Financeiro",
    ativo: true,
    dataCadastro: "28/02/2024",
  },
];
