import { Usuario } from "./types";

export const perfis = ["Administrador", "Back Office", "Técnico"];

export const mockUsuarios: Usuario[] = [
  {
    id: 1,
    nome: "João Silva",
    email: "joao.silva@empresa.com",
    departamento: "TI",
    perfil: 1,
    telefone: "(11) 99999-9999",
    senha: "senha123",
    confirmarSenha: "senha123",
    ativo: true,
    dataCadastro: "15/01/2024",
  },
  {
    id: 2,
    nome: "Maria Santos",
    email: "maria.santos@empresa.com",
    departamento: "RH",
    perfil: 2,
    telefone: "(11) 98888-8888",
    senha: "senha123",
    confirmarSenha: "senha123",
    ativo: true,
    dataCadastro: "20/01/2024",
  },
  {
    id: 3,
    nome: "Pedro Oliveira",
    email: "pedro.oliveira@empresa.com",
    departamento: "Financeiro",
    perfil: 3,
    telefone: "(11) 97777-7777",
    senha: "senha123",
    confirmarSenha: "senha123",
    ativo: false,
    dataCadastro: "05/02/2024",
  },
  {
    id: 4,
    nome: "Ana Costa",
    email: "ana.costa@empresa.com",
    departamento: "Marketing",
    perfil: 2,
    telefone: "(11) 96666-6666",
    senha: "senha123",
    confirmarSenha: "senha123",
    ativo: true,
    dataCadastro: "10/02/2024",
  },
  {
    id: 5,
    nome: "Carlos Lima",
    email: "carlos.lima@empresa.com",
    departamento: "TI",
    perfil: 1,
    telefone: "(11) 95555-5555",
    senha: "senha123",
    confirmarSenha: "senha123",
    ativo: true,
    dataCadastro: "15/02/2024",
  },
  {
    id: 6,
    nome: "Juliana Pereira",
    email: "juliana.pereira@empresa.com",
    departamento: "Vendas",
    perfil: 2,
    telefone: "(11) 94444-4444",
    senha: "senha123",
    confirmarSenha: "senha123",
    ativo: true,
    dataCadastro: "01/03/2024",
  },
  {
    id: 7,
    nome: "Ricardo Almeida",
    email: "ricardo.almeida@empresa.com",
    departamento: "Operações",
    perfil: 3,
    telefone: "(11) 93333-3333",
    senha: "senha123",
    confirmarSenha: "senha123",
    ativo: false,
    dataCadastro: "05/03/2024",
  },
  {
    id: 8,
    nome: "Fernanda Souza",
    email: "fernanda.souza@empresa.com",
    departamento: "RH",
    perfil: 1,
    telefone: "(11) 92222-2222",
    senha: "senha123",
    confirmarSenha: "senha123",
    ativo: true,
    dataCadastro: "10/03/2024",
  },
  {
    id: 9,
    nome: "Roberto Martins",
    email: "roberto.martins@empresa.com",
    departamento: "Financeiro",
    perfil: 2,
    telefone: "(11) 91111-1111",
    senha: "senha123",
    confirmarSenha: "senha123",
    ativo: true,
    dataCadastro: "15/03/2024",
  },
  {
    id: 10,
    nome: "Amanda Rodrigues",
    email: "amanda.rodrigues@empresa.com",
    departamento: "Marketing",
    perfil: 3,
    telefone: "(11) 90000-0000",
    senha: "senha123",
    confirmarSenha: "senha123",
    ativo: true,
    dataCadastro: "20/03/2024",
  },
  {
    id: 11,
    nome: "Bruno Ferreira",
    email: "bruno.ferreira@empresa.com",
    departamento: "TI",
    perfil: 1,
    telefone: "(11) 89999-9999",
    senha: "senha123",
    confirmarSenha: "senha123",
    ativo: false,
    dataCadastro: "01/04/2024",
  },
  {
    id: 12,
    nome: "Patrícia Gomes",
    email: "patricia.gomes@empresa.com",
    departamento: "Vendas",
    perfil: 2,
    telefone: "(11) 88888-8888",
    senha: "senha123",
    confirmarSenha: "senha123",
    ativo: true,
    dataCadastro: "05/04/2024",
  },
  {
    id: 13,
    nome: "Daniel Barbosa",
    email: "daniel.barbosa@empresa.com",
    departamento: "Operações",
    perfil: "",
    telefone: "(11) 87777-7777",
    senha: "senha123",
    confirmarSenha: "senha123",
    ativo: true,
    dataCadastro: null,
  },
  {
    id: 14,
    nome: "Luciana Teixeira",
    email: "luciana.teixeira@empresa.com",
    departamento: "RH",
    perfil: 2,
    telefone: "(11) 86666-6666",
    senha: "senha123",
    confirmarSenha: "senha123",
    ativo: true,
    dataCadastro: "15/04/2024",
  },
  {
    id: 15,
    nome: "Marcos Rocha",
    email: "marcos.rocha@empresa.com",
    departamento: "Financeiro",
    perfil: 3,
    telefone: "(11) 85555-5555",
    senha: "senha123",
    confirmarSenha: "senha123",
    ativo: false,
    dataCadastro: "20/04/2024",
  },
  {
    id: 16,
    nome: "Tatiane Moreira",
    email: "tatiane.moreira@empresa.com",
    departamento: "",
    perfil: 1,
    telefone: "(11) 84444-4444",
    senha: "senha123",
    confirmarSenha: "senha123",
    ativo: true,
    dataCadastro: "01/05/2024",
  },
  {
    id: 17,
    nome: "Eduardo Santos",
    email: "eduardo.santos@empresa.com",
    departamento: "TI",
    perfil: 2,
    telefone: "(11) 83333-3333",
    senha: "senha123",
    confirmarSenha: "senha123",
    ativo: true,
    dataCadastro: "05/05/2024",
  },
  {
    id: 18,
    nome: "Vanessa Lima",
    email: "vanessa.lima@empresa.com",
    departamento: "Marketing",
    perfil: "",
    telefone: "(11) 82222-2222",
    senha: "senha123",
    confirmarSenha: "senha123",
    ativo: false,
    dataCadastro: null,
  },
  {
    id: 19,
    nome: "Fábio Costa",
    email: "fabio.costa@empresa.com",
    departamento: "Vendas",
    perfil: 3,
    telefone: "(11) 81111-1111",
    senha: "senha123",
    confirmarSenha: "senha123",
    ativo: true,
    dataCadastro: "15/05/2024",
  },
  {
    id: 20,
    nome: "Simone Alves",
    email: "simone.alves@empresa.com",
    departamento: "Operações",
    perfil: 2,
    telefone: "(11) 80000-0000",
    senha: "senha123",
    confirmarSenha: "senha123",
    ativo: true,
    dataCadastro: "20/05/2024",
  },
];
