import { NaoConformidades } from "./types";

export const mockNaoConformidades: NaoConformidades[] = [
  {
    OS: 1001,
    data: "15/03/2024",
    areaELocal: "Produção - Linha de Montagem 3",
    naoConformidade: "Peça com dimensões fora da especificação",
    acaoSugerida: "Revisar calibração da máquina de corte",
  },
  {
    OS: 1002,
    data: "10/03/2024",
    areaELocal: "Qualidade - Laboratório de Testes",
    naoConformidade: "Teste de resistência falhou no lote #245",
    acaoSugerida: "Isolar lote e realizar reteste completo",
  },
  {
    OS: 1003,
    data: null,
    areaELocal: "Almoxarifado - Setor de Matéria-Prima",
    naoConformidade: "Material armazenado em local incorreto",
    acaoSugerida: "Retreinar equipe sobre procedimentos de armazenamento",
  },
  {
    OS: 1004,
    data: "05/03/2024",
    areaELocal: "Logística - Doca de Carga",
    naoConformidade: "Embalagem danificada durante carregamento",
    acaoSugerida: "Implementar checklist pré-carga",
  },
  {
    OS: 1005,
    data: "28/02/2024",
    areaELocal: "Manutenção - Máquina Prensa 2",
    naoConformidade: "Vazamento de óleo hidráulico",
    acaoSugerida: "Substituir selos e realizar manutenção preventiva",
  },
  {
    OS: 1006,
    data: "22/02/2024",
    areaELocal: "RH - Sala de Treinamento",
    naoConformidade: "Documentação de treinamento desatualizada",
    acaoSugerida: "Atualizar manuais e procedimentos",
  },
  {
    OS: 1007,
    data: "18/02/2024",
    areaELocal: "Produção - Linha de Pintura",
    naoConformidade: "Espessura de tinta abaixo do especificado",
    acaoSugerida: "Calibrar equipamentos e verificar viscosidade",
  },
  {
    OS: 1008,
    data: "12/02/2024",
    areaELocal: "Qualidade - Inspeção Final",
    naoConformidade: "Produto com arranhões na superfície",
    acaoSugerida: "Inspecionar esteiras de transporte",
  },
  {
    OS: 1009,
    data: "08/02/2024",
    areaELocal: "Expedição - Área de Separação",
    naoConformidade: "Pedido com itens incorretos",
    acaoSugerida: "Implementar dupla checagem no picking",
  },
  {
    OS: 1010,
    data: "02/02/2024",
    areaELocal: "Laboratório - Análise Química",
    naoConformidade: "Reagente vencido utilizado em teste",
    acaoSugerida: "Implementar sistema de controle de validade",
  },
  {
    OS: 1011,
    data: "28/01/2024",
    areaELocal: "Produção - Solda MIG",
    naoConformidade: "Solda com porosidade excessiva",
    acaoSugerida: "Verificar regulagem de gás e corrente",
  },
  {
    OS: 1012,
    data: "25/01/2024",
    areaELocal: "Almoxarifado - Estoque de EPIs",
    naoConformidade: "EPI vencido disponível para uso",
    acaoSugerida: "Realizar auditoria mensal de validade",
  },
  {
    OS: 1013,
    data: "20/01/2024",
    areaELocal: "Manutenção - Subestação Elétrica",
    naoConformidade: "Falta de sinalização de segurança",
    acaoSugerida: "Instalar placas de alerta e procedimentos",
  },
  {
    OS: 1014,
    data: "15/01/2024",
    areaELocal: "Produção - Máquina CNC 4",
    naoConformidade: "Ferramenta desgastada causando imperfeições",
    acaoSugerida: "Implementar controle de vida útil de ferramentas",
  },
  {
    OS: 1015,
    data: "10/01/2024",
    areaELocal: "Qualidade - Metrologia",
    naoConformidade: "Instrumento de medição com calibração vencida",
    acaoSugerida: "Atualizar sistema de controle de calibração",
  },
  {
    OS: 1016,
    data: "05/01/2024",
    areaELocal: "Logística - Recebimento",
    naoConformidade: "Nota fiscal divergente da quantidade recebida",
    acaoSugerida: "Capacitar equipe em procedimentos de recebimento",
  },
  {
    OS: 1017,
    data: "02/01/2024",
    areaELocal: "Produção - Linha de Embalagem",
    naoConformidade: "Etiqueta com informações incorretas",
    acaoSugerida: "Validar dados antes de iniciar produção",
  },
  {
    OS: 1018,
    data: "28/12/2023",
    areaELocal: "Administração - Arquivo de Documentos",
    naoConformidade: "Documento de processo não assinado",
    acaoSugerida: "Implementar controle de aprovação documental",
  },
  {
    OS: 1019,
    data: "22/12/2023",
    areaELocal: "Manutenção - Compressor Central",
    naoConformidade: "Nível de ruído acima do permitido",
    acaoSugerida: "Realizar manutenção corretiva no isolamento acústico",
  },
  {
    OS: 1020,
    data: "18/12/2023",
    areaELocal: "Qualidade - Auditoria Interna",
    naoConformidade: "Não conformidade recorrente não tratada",
    acaoSugerida: "Implementar plano de ação com follow-up periódico",
  },
];
