import { OrdemDeServico, Status } from "./types";

export const mockOrdensDeServico: OrdemDeServico[] = [
  {
    id: 1,
    status: Status.PENDENTE,
    data: "2024-01-15",
    horaInicio: "09:00",
    horaFim: "12:30",
    tecnico: { id: 1, nome: "Carlos Silva" },
  },
  {
    id: 3,
    status: Status.CANCELADO,
    data: "2024-01-13",
    horaInicio: "10:15",
    horaFim: "13:15",
    tecnico: {
      id: 3,
      nome: "Roberto Almeida",
    },
  },
  {
    id: 5,
    status: Status.PENDENTE,
    data: "2024-01-16",
    horaInicio: "13:45",
    horaFim: "15:20",
    tecnico: {
      id: 5,
      nome: "Marcos Oliveira",
    },
  },
  {
    id: 6,
    status: Status.REALIZADO,
    data: "2024-01-12",
    horaInicio: "16:00",
    horaFim: "19:25",
    tecnico: { id: 1, nome: "Carlos Silva" },
  },
  {
    id: 8,
    status: Status.PENDENTE,
    data: "2024-01-17",
    horaInicio: "15:30",
    horaFim: "16:50",
    tecnico: {
      id: 3,
      nome: "Roberto Almeida",
    },
  },
  {
    id: 9,
    status: Status.CANCELADO,
    data: "2024-01-10",
    horaInicio: "10:00",
    horaFim: "15:35",
    tecnico: {
      id: 4,
      nome: "Fernanda Costa",
    },
  },
  {
    id: 10,
    status: Status.PENDENTE,
    data: "2024-01-18",
    horaInicio: "09:15",
    horaFim: "15:45",
    tecnico: {
      id: 5,
      nome: "Marcos Oliveira",
    },
  },
  {
    id: 11,
    status: Status.REALIZADO,
    data: "2024-01-09",
    horaInicio: "14:00",
    horaFim: "17:30",
    tecnico: { id: 1, nome: "Carlos Silva" },
  },
  {
    id: 13,
    status: Status.REALIZADO,
    data: "2024-01-08",
    horaInicio: "13:15",
    horaFim: "18:20",
    tecnico: {
      id: 3,
      nome: "Roberto Almeida",
    },
  },
  {
    id: 15,
    status: Status.CANCELADO,
    data: "2024-01-07",
    horaInicio: "09:45",
    horaFim: "11:00",
    tecnico: {
      id: 5,
      nome: "Marcos Oliveira",
    },
  },
  {
    id: 16,
    status: Status.PENDENTE,
    data: "2024-01-21",
    horaInicio: "10:30",
    horaFim: "13:10",
    tecnico: { id: 1, nome: "Carlos Silva" },
  },
  {
    id: 18,
    status: Status.PENDENTE,
    data: "2024-01-22",
    horaInicio: "14:15",
    horaFim: "15:15",
    tecnico: {
      id: 3,
      nome: "Roberto Almeida",
    },
  },
  {
    id: 20,
    status: Status.REALIZADO,
    data: "2024-01-05",
    horaInicio: "12:00",
    horaFim: "16:20",
    tecnico: {
      id: null,
      nome: "Técnico Indefinido",
    },
  },
];
