import { Cliente } from "../../services/Clientes/types";

export const estados = [
  "Acre",
  "Alagoas",
  "Amapá",
  "Amazonas",
  "Bahia",
  "Ceará",
  "Distrito Federal",
  "Espírito Santo",
  "Goiás",
  "Maranhão",
  "Mato Grosso",
  "Mato Grosso do Sul",
  "Minas Gerais",
  "Pará",
  "Paraíba",
  "Paraná",
  "Pernambuco",
  "Piauí",
  "Rio de Janeiro",
  "Rio Grande do Norte",
  "Rio Grande do Sul",
  "Rondônia",
  "Roraima",
  "Santa Catarina",
  "São Paulo",
  "Sergipe",
  "Tocantins",
];

export const mockClientes: Cliente[] = [
  {
    id: 1,
    razaoSocial: "Tech Solutions Brasil Ltda",
    nomeFantasia: "Tech Solutions",
    cnpjCpf: "12345678000195",
    validadeCertificado: 365,
    tipoAtividade: "Tecnologia e Consultoria",
    possuiContrato: true,
    logradouro: "Av. Paulista",
    numero: "1000",
    complemento: "Conjunto 101",
    bairro: "Bela Vista",
    estado: 35,
    cidade: "São Paulo",
    cep: "01311000",
    contato: "João Silva",
    telefone: "(11) 9999-8888",
    funcao: "Gerente Comercial",
    fax: "(11) 9999-8887",
    email: "joao.silva@techsolutions.com.br",
    observacoes: "Cliente preferencial com histórico de pagamentos em dia",
    nomeAcesso: "joao.silva",
    emailAcesso: "joao.silva@techsolutions.com.br",
    departamento: "Comercial",
    senha: "123456",
    confirmarSenha: "123456",
    ativo: true,
    dataCadastro: "20/10/2025",
  },
  {
    id: 2,
    razaoSocial: "Indústrias Metalúrgicas São José S.A.",
    nomeFantasia: "Metal São José",
    cnpjCpf: "98765432000146",
    validadeCertificado: 180,
    tipoAtividade: "Indústria Metalúrgica",
    possuiContrato: false,
    logradouro: "Rua das Indústrias",
    numero: "250",
    complemento: "Galpão A",
    bairro: "Industrial",
    estado: 31,
    cidade: "Belo Horizonte",
    cep: "30130000",
    contato: "Maria Oliveira",
    telefone: "(31) 8888-7777",
    funcao: "Diretora Industrial",
    fax: "(31) 8888-7776",
    email: "maria.oliveira@metalsj.com.br",
    observacoes: "Necessita visita técnica mensal",
    nomeAcesso: "maria.oliveira",
    emailAcesso: "maria.oliveira@metalsj.com.br",
    departamento: "Industrial",
    senha: "123456",
    confirmarSenha: "123456",
    ativo: true,
    dataCadastro: "20/10/2025",
  },
  {
    id: 3,
    razaoSocial: "Comércio de Alimentos Natural Ltda",
    nomeFantasia: "Natural Foods",
    cnpjCpf: "45678912000133",
    validadeCertificado: 90,
    tipoAtividade: "Comércio Varejista",
    possuiContrato: true,
    logradouro: "Rua das Flores",
    numero: "150",
    complemento: "Loja 05",
    bairro: "Centro",
    estado: 33,
    cidade: "Rio de Janeiro",
    cep: "20040000",
    contato: "Carlos Santos",
    telefone: "(21) 7777-6666",
    funcao: "Proprietário",
    fax: "(21) 7777-6665",
    email: "carlos.santos@naturalfoods.com.br",
    observacoes: "Cliente novo, primeira certificação",
    nomeAcesso: "carlos.santos",
    emailAcesso: "carlos.santos@naturalfoods.com.br",
    departamento: "Administrativo",
    senha: "123456",
    confirmarSenha: "123456",
    ativo: true,
    dataCadastro: "20/10/2025",
  },
  {
    id: 4,
    razaoSocial: "Construções e Edificações Moderna S.A.",
    nomeFantasia: "Construmoderna",
    cnpjCpf: "32165498000177",
    validadeCertificado: 270,
    tipoAtividade: "Construção Civil",
    possuiContrato: true,
    logradouro: "Av. das Construções",
    numero: "500",
    complemento: "Sala 302",
    bairro: "Jardim América",
    estado: 35,
    cidade: "Campinas",
    cep: "13015000",
    contato: "Roberto Ferreira",
    telefone: "(19) 6666-5555",
    funcao: "Engenheiro Responsável",
    fax: "(19) 6666-5554",
    email: "roberto.ferreira@construmoderna.com.br",
    observacoes: "Possui múltiplas obras ativas",
    nomeAcesso: "roberto.ferreira",
    emailAcesso: "roberto.ferreira@construmoderna.com.br",
    departamento: "Engenharia",
    senha: "123456",
    confirmarSenha: "123456",
    ativo: false,
    dataCadastro: "20/10/2025",
  },
  {
    id: 5,
    razaoSocial: "Transportes Rápidos Express Ltda",
    nomeFantasia: "TranspExpress",
    cnpjCpf: "65412378000122",
    validadeCertificado: 365,
    tipoAtividade: "Transporte e Logística",
    possuiContrato: false,
    logradouro: "Rodovia dos Imigrantes",
    numero: "KM 10",
    complemento: "Pátio 03",
    bairro: "Distrito Industrial",
    estado: 35,
    cidade: "Santos",
    cep: "11015000",
    contato: "Ana Costa",
    telefone: "(13) 5555-4444",
    funcao: "Coordenadora de Logística",
    fax: "(13) 5555-4443",
    email: "ana.costa@transpexpress.com.br",
    observacoes: "Frota de 25 caminhões",
    nomeAcesso: "ana.costa",
    emailAcesso: "ana.costa@transpexpress.com.br",
    departamento: "Logística",
    senha: "123456",
    confirmarSenha: "123456",
    ativo: true,
    dataCadastro: "20/10/2025",
  },
  {
    id: 6,
    razaoSocial: "Consultoria Empresarial Avançada Ltda",
    nomeFantasia: "ConsultAvance",
    cnpjCpf: "78945613000188",
    validadeCertificado: 120,
    tipoAtividade: "Consultoria Empresarial",
    possuiContrato: true,
    logradouro: "Alameda Santos",
    numero: "800",
    complemento: "Andar 8",
    bairro: "Jardins",
    estado: 35,
    cidade: "São Paulo",
    cep: "01418000",
    contato: "Paula Rodrigues",
    telefone: "(11) 4444-3333",
    funcao: "Sócia Diretora",
    fax: "(11) 4444-3332",
    email: "paula.rodrigues@consultavance.com.br",
    observacoes: "Especializada em PMEs",
    nomeAcesso: "paula.rodrigues",
    emailAcesso: "paula.rodrigues@consultavance.com.br",
    departamento: "Diretoria",
    senha: "123456",
    confirmarSenha: "123456",
    ativo: true,
    dataCadastro: "20/10/2025",
  },
  {
    id: 7,
    razaoSocial: "Laboratório Farmacêutico Vital S.A.",
    nomeFantasia: "LabVital",
    cnpjCpf: "15975346000199",
    validadeCertificado: 365,
    tipoAtividade: "Indústria Farmacêutica",
    possuiContrato: true,
    logradouro: "Rua da Saúde",
    numero: "350",
    complemento: "Bloco B",
    bairro: "Medicinal",
    estado: 23,
    cidade: "Fortaleza",
    cep: "60000000",
    contato: "Dr. Fernando Lima",
    telefone: "(85) 3333-2222",
    funcao: "Diretor Técnico",
    fax: "(85) 3333-2221",
    email: "fernando.lima@labvital.com.br",
    observacoes: "Certificação ANVISA pendente",
    nomeAcesso: "fernando.lima",
    emailAcesso: "fernando.lima@labvital.com.br",
    departamento: "Técnico",
    senha: "123456",
    confirmarSenha: "123456",
    ativo: true,
    dataCadastro: "20/10/2025",
  },
  {
    id: 8,
    razaoSocial: "Vestuário Moda Fashion Ltda",
    nomeFantasia: "Fashion Wear",
    cnpjCpf: "35795182000144",
    validadeCertificado: 60,
    tipoAtividade: "Confecção e Varejo",
    possuiContrato: false,
    logradouro: "Rua da Moda",
    numero: "75",
    complemento: "Loja 12",
    bairro: "Brotas",
    estado: 29,
    cidade: "Salvador",
    cep: "40000000",
    contato: "Juliana Almeida",
    telefone: "(71) 2222-1111",
    funcao: "Estilista Chefe",
    fax: "(71) 2222-1110",
    email: "juliana.almeida@fashionwear.com.br",
    observacoes: "Coleção outono/inverno em produção",
    nomeAcesso: "juliana.almeida",
    emailAcesso: "juliana.almeida@fashionwear.com.br",
    departamento: "Criação",
    senha: "123456",
    confirmarSenha: "123456",
    ativo: true,
    dataCadastro: "20/10/2025",
  },
  {
    id: 9,
    razaoSocial: "Educação e Ensino Superior Ltda",
    nomeFantasia: "Faculdade Progresso",
    cnpjCpf: "25874196000155",
    validadeCertificado: 365,
    tipoAtividade: "Educação Superior",
    possuiContrato: true,
    logradouro: "Av. dos Universitários",
    numero: "1200",
    complemento: "Campus Central",
    bairro: "Universitário",
    estado: 31,
    cidade: "Uberlândia",
    cep: "38400000",
    contato: "Prof. Marcelo Dias",
    telefone: "(34) 1111-0000",
    funcao: "Coordenador Geral",
    fax: "(34) 1111-0001",
    email: "marcelo.dias@faculdadeprogresso.com.br",
    observacoes: "MEC nota 4",
    nomeAcesso: "marcelo.dias",
    emailAcesso: "marcelo.dias@faculdadeprogresso.com.br",
    departamento: "Acadêmico",
    senha: "123456",
    confirmarSenha: "123456",
    ativo: false,
    dataCadastro: "20/10/2025",
  },
  {
    id: 10,
    razaoSocial: "Hotelaria e Turismo Praiano S.A.",
    nomeFantasia: "Praia Hotel",
    cnpjCpf: "75315982000166",
    validadeCertificado: 180,
    tipoAtividade: "Hotelaria e Turismo",
    possuiContrato: true,
    logradouro: "Av. Beira Mar",
    numero: "2500",
    complemento: "",
    bairro: "Praia do Futuro",
    estado: 23,
    cidade: "Fortaleza",
    cep: "60165000",
    contato: "Sandra Nunes",
    telefone: "(85) 9999-8888",
    funcao: "Gerente Geral",
    fax: "(85) 9999-8887",
    email: "sandra.nunes@praiahotel.com.br",
    observacoes: "Temporada alta: dezembro a fevereiro",
    nomeAcesso: "sandra.nunes",
    emailAcesso: "sandra.nunes@praiahotel.com.br",
    departamento: "Administração",
    senha: "123456",
    confirmarSenha: "123456",
    ativo: true,
    dataCadastro: "20/10/2025",
  },
  {
    id: 11,
    razaoSocial: "Agropecuária Produtiva Ltda",
    nomeFantasia: "AgroProdutiva",
    cnpjCpf: "85274196000177",
    validadeCertificado: 365,
    tipoAtividade: "Agropecuária",
    possuiContrato: false,
    logradouro: "Fazenda São João",
    numero: "S/N",
    complemento: "Zona Rural",
    bairro: "",
    estado: 50,
    cidade: "Campo Grande",
    cep: "79000000",
    contato: "José Pereira",
    telefone: "(67) 8888-7777",
    funcao: "Produtor Rural",
    fax: "(67) 8888-7776",
    email: "jose.pereira@agroprodutiva.com.br",
    observacoes: "Produção de soja e milho",
    nomeAcesso: "jose.pereira",
    emailAcesso: "jose.pereira@agroprodutiva.com.br",
    departamento: "Produção",
    senha: "123456",
    confirmarSenha: "123456",
    ativo: true,
    dataCadastro: "20/10/2025",
  },
  {
    id: 12,
    razaoSocial: "Informática e Soluções Digitais Ltda",
    nomeFantasia: "InfoDigital",
    cnpjCpf: "96385274000188",
    validadeCertificado: 365,
    tipoAtividade: "Tecnologia da Informação",
    possuiContrato: true,
    logradouro: "Rua dos Computadores",
    numero: "45",
    complemento: "Sala 501",
    bairro: "Centro",
    estado: 43,
    cidade: "Porto Alegre",
    cep: "90000000",
    contato: "Ricardo Souza",
    telefone: "(51) 7777-6666",
    funcao: "CTO",
    fax: "(51) 7777-6665",
    email: "ricardo.souza@infodigital.com.br",
    observacoes: "Especializada em desenvolvimento web",
    nomeAcesso: "ricardo.souza",
    emailAcesso: "ricardo.souza@infodigital.com.br",
    departamento: "Tecnologia",
    senha: "123456",
    confirmarSenha: "123456",
    ativo: true,
    dataCadastro: "20/10/2025",
  },
  {
    id: 13,
    razaoSocial: "Restaurante Sabor Caseiro Ltda",
    nomeFantasia: "Sabor Caseiro",
    cnpjCpf: "74185296000199",
    validadeCertificado: 90,
    tipoAtividade: "Alimentação",
    possuiContrato: false,
    logradouro: "Praça da Alimentação",
    numero: "30",
    complemento: "Shopping Center",
    bairro: "Centro",
    estado: 41,
    cidade: "Curitiba",
    cep: "80000000",
    contato: "Mariana Costa",
    telefone: "(41) 6666-5555",
    funcao: "Proprietária",
    fax: "(41) 6666-5554",
    email: "mariana.costa@saborcaseiro.com.br",
    observacoes: "Cardápio regional",
    nomeAcesso: "mariana.costa",
    emailAcesso: "mariana.costa@saborcaseiro.com.br",
    departamento: "Administrativo",
    senha: "123456",
    confirmarSenha: "123456",
    ativo: true,
    dataCadastro: "20/10/2025",
  },
  {
    id: 14,
    razaoSocial: "Auto Peças e Serviços Ltda",
    nomeFantasia: "AutoParts",
    cnpjCpf: "36925814000111",
    validadeCertificado: 270,
    tipoAtividade: "Comércio de Autopeças",
    possuiContrato: true,
    logradouro: "Av. Automotiva",
    numero: "600",
    complemento: "Galpão 02",
    bairro: "Industrial",
    estado: 35,
    cidade: "São Bernardo do Campo",
    cep: "09725000",
    contato: "Carlos Mendes",
    telefone: "(11) 5555-4444",
    funcao: "Vendedor Sênior",
    fax: "(11) 5555-4443",
    email: "carlos.mendes@autoparts.com.br",
    observacoes: "Atende todo ABC Paulista",
    nomeAcesso: "carlos.mendes",
    emailAcesso: "carlos.mendes@autoparts.com.br",
    departamento: "Vendas",
    senha: "123456",
    confirmarSenha: "123456",
    ativo: true,
    dataCadastro: "20/10/2025",
  },
  {
    id: 15,
    razaoSocial: "Clínica Médica Especializada Ltda",
    nomeFantasia: "Clínica Saúde Total",
    cnpjCpf: "14725836000122",
    validadeCertificado: 365,
    tipoAtividade: "Serviços de Saúde",
    possuiContrato: true,
    logradouro: "Rua dos Médicos",
    numero: "85",
    complemento: "Consultório 201",
    bairro: "Jardim Saúde",
    estado: 53,
    cidade: "Brasília",
    cep: "70000000",
    contato: "Dra. Patrícia Rocha",
    telefone: "(61) 4444-3333",
    funcao: "Médica Responsável",
    fax: "(61) 4444-3332",
    email: "patricia.rocha@clinicasaudetotal.com.br",
    observacoes: "Especializada em cardiologia",
    nomeAcesso: "patricia.rocha",
    emailAcesso: "patricia.rocha@clinicasaudetotal.com.br",
    departamento: "Médico",
    senha: "123456",
    confirmarSenha: "123456",
    ativo: true,
    dataCadastro: "20/10/2025",
  },
];
