export const estados = [
  "Acre",
  "Alagoas",
  "Amapá",
  "Amazonas",
  "Bahia",
  "Ceará",
  "Distrito Federal",
  "Espírito Santo",
  "Goiás",
  "Maranhão",
  "Mato Grosso",
  "Mato Grosso do Sul",
  "Minas Gerais",
  "Pará",
  "Paraíba",
  "Paraná",
  "Pernambuco",
  "Piauí",
  "Rio de Janeiro",
  "Rio Grande do Norte",
  "Rio Grande do Sul",
  "Rondônia",
  "Roraima",
  "Santa Catarina",
  "São Paulo",
  "Sergipe",
  "Tocantins",
];

export const mockOrdemDeServicos = [
  {
    numero: 1,
    cliente: "Empresa ABC Ltda",
    tecnico: "João Silva",
    dataHora: {
      data: "2024-01-15",
      horaDe: "08:00",
      horaAte: "12:00",
    },
    ativo: true,
  },
  {
    numero: 2,
    cliente: "Comércio XYZ S/A",
    tecnico: "Maria Santos",
    dataHora: {
      data: "2024-01-15",
      horaDe: "09:30",
      horaAte: "11:30",
    },
    ativo: true,
  },
  {
    numero: 3,
    cliente: "Indústria 123 ME",
    tecnico: "Pedro Oliveira",
    dataHora: {
      data: "2024-01-16",
      horaDe: "14:00",
      horaAte: "17:00",
    },
    ativo: false,
  },
  {
    numero: 4,
    cliente: "Serviços Quick Ltda",
    tecnico: "Ana Costa",
    dataHora: {
      data: "2024-01-16",
      horaDe: "10:00",
      horaAte: "12:00",
    },
    ativo: true,
  },
  {
    numero: 5,
    cliente: "Tech Solutions BR",
    tecnico: "Carlos Mendes",
    dataHora: {
      data: "2024-01-17",
      horaDe: "08:30",
      horaAte: "11:30",
    },
    ativo: true,
  },
  {
    numero: 6,
    cliente: "Alimentos Natural",
    tecnico: "João Silva",
    dataHora: {
      data: "2024-01-17",
      horaDe: "13:00",
      horaAte: "16:00",
    },
    ativo: true,
  },
  {
    numero: 7,
    cliente: "Construção Forte",
    tecnico: "Maria Santos",
    dataHora: {
      data: "2024-01-18",
      horaDe: "09:00",
      horaAte: "12:00",
    },
    ativo: false,
  },
  {
    numero: 8,
    cliente: "Auto Peças Rapid",
    tecnico: "Pedro Oliveira",
    dataHora: {
      data: "2024-01-18",
      horaDe: "14:30",
      horaAte: "17:30",
    },
    ativo: true,
  },
  {
    numero: 9,
    cliente: "Consultoria Elite",
    tecnico: "Ana Costa",
    dataHora: {
      data: "2024-01-19",
      horaDe: "08:00",
      horaAte: "10:00",
    },
    ativo: true,
  },
  {
    numero: 10,
    cliente: "Logística Express",
    tecnico: "Carlos Mendes",
    dataHora: {
      data: "2024-01-19",
      horaDe: "11:00",
      horaAte: "13:00",
    },
    ativo: true,
  },
  {
    numero: 11,
    cliente: "Farmácia Saúde",
    tecnico: "João Silva",
    dataHora: {
      data: "2024-01-22",
      horaDe: "15:00",
      horaAte: "18:00",
    },
    ativo: false,
  },
  {
    numero: 12,
    cliente: "Escola Futuro",
    tecnico: "Maria Santos",
    dataHora: {
      data: "2024-01-22",
      horaDe: "08:00",
      horaAte: "12:00",
    },
    ativo: true,
  },
  {
    numero: 13,
    cliente: "Hotel Confort",
    tecnico: "Pedro Oliveira",
    dataHora: {
      data: "2024-01-23",
      horaDe: "10:00",
      horaAte: "14:00",
    },
    ativo: true,
  },
  {
    numero: 14,
    cliente: "Restaurante Sabor",
    tecnico: "Ana Costa",
    dataHora: {
      data: "2024-01-23",
      horaDe: "16:00",
      horaAte: "19:00",
    },
    ativo: true,
  },
  {
    numero: 15,
    cliente: "Mercado Popular",
    tecnico: "Carlos Mendes",
    dataHora: {
      data: "2024-01-24",
      horaDe: "07:00",
      horaAte: "10:00",
    },
    ativo: false,
  },
  {
    numero: 16,
    cliente: "Academia Fit",
    tecnico: "João Silva",
    dataHora: {
      data: "2024-01-24",
      horaDe: "13:00",
      horaAte: "15:00",
    },
    ativo: true,
  },
  {
    numero: 17,
    cliente: "Oficina Mecânica",
    tecnico: "Maria Santos",
    dataHora: {
      data: "2024-01-25",
      horaDe: "09:30",
      horaAte: "12:30",
    },
    ativo: true,
  },
  {
    numero: 18,
    cliente: "Salão Beauty",
    tecnico: "Pedro Oliveira",
    dataHora: {
      data: "2024-01-25",
      horaDe: "14:00",
      horaAte: "17:00",
    },
    ativo: true,
  },
  {
    numero: 19,
    cliente: "Transportes Rápido",
    tecnico: "Ana Costa",
    dataHora: {
      data: "2024-01-26",
      horaDe: "08:00",
      horaAte: "11:00",
    },
    ativo: false,
  },
  {
    numero: 20,
    cliente: "Informática Tech",
    tecnico: "Carlos Mendes",
    dataHora: {
      data: "2024-01-26",
      horaDe: "12:00",
      horaAte: "15:00",
    },
    ativo: true,
  },
  {
    numero: 21,
    cliente: "Construção Moderna",
    tecnico: "João Silva",
    dataHora: {
      data: "2024-01-29",
      horaDe: "10:00",
      horaAte: "13:00",
    },
    ativo: true,
  },
  {
    numero: 22,
    cliente: "Supermercado Bom",
    tecnico: "Maria Santos",
    dataHora: {
      data: "2024-01-29",
      horaDe: "14:30",
      horaAte: "17:30",
    },
    ativo: true,
  },
  {
    numero: 23,
    cliente: "Clínica Médica",
    tecnico: "Pedro Oliveira",
    dataHora: {
      data: "2024-01-30",
      horaDe: "08:00",
      horaAte: "10:00",
    },
    ativo: false,
  },
  {
    numero: 24,
    cliente: "Padaria Pão Quente",
    tecnico: "Ana Costa",
    dataHora: {
      data: "2024-01-30",
      horaDe: "11:00",
      horaAte: "13:00",
    },
    ativo: true,
  },
  {
    numero: 25,
    cliente: "Loja Departamental",
    tecnico: "Carlos Mendes",
    dataHora: {
      data: "2024-01-31",
      horaDe: "15:00",
      horaAte: "18:00",
    },
    ativo: true,
  },
  {
    numero: 26,
    cliente: "Posto Combustível",
    tecnico: "João Silva",
    dataHora: {
      data: "2024-01-31",
      horaDe: "09:00",
      horaAte: "12:00",
    },
    ativo: true,
  },
  {
    numero: 27,
    cliente: "Lavanderia Clean",
    tecnico: "Maria Santos",
    dataHora: {
      data: "2024-02-01",
      horaDe: "13:00",
      horaAte: "16:00",
    },
    ativo: false,
  },
  {
    numero: 28,
    cliente: "Pet Shop Amigo",
    tecnico: "Pedro Oliveira",
    dataHora: {
      data: "2024-02-01",
      horaDe: "10:30",
      horaAte: "12:30",
    },
    ativo: true,
  },
  {
    numero: 29,
    cliente: "Barbearia Style",
    tecnico: "Ana Costa",
    dataHora: {
      data: "2024-02-02",
      horaDe: "08:00",
      horaAte: "11:00",
    },
    ativo: true,
  },
  {
    numero: 30,
    cliente: "Locadora Auto",
    tecnico: "Carlos Mendes",
    dataHora: {
      data: "2024-02-02",
      horaDe: "14:00",
      horaAte: "17:00",
    },
    ativo: true,
  },
  {
    numero: 31,
    cliente: "Joalheria Brilho",
    tecnico: "João Silva",
    dataHora: {
      data: "2024-02-05",
      horaDe: "09:00",
      horaAte: "11:00",
    },
    ativo: false,
  },
  {
    numero: 32,
    cliente: "Livraria Cultura",
    tecnico: "Maria Santos",
    dataHora: {
      data: "2024-02-05",
      horaDe: "13:30",
      horaAte: "16:30",
    },
    ativo: true,
  },
  {
    numero: 33,
    cliente: "Cinema City",
    tecnico: "Pedro Oliveira",
    dataHora: {
      data: "2024-02-06",
      horaDe: "10:00",
      horaAte: "13:00",
    },
    ativo: true,
  },
  {
    numero: 34,
    cliente: "Laboratório Análises",
    tecnico: "Ana Costa",
    dataHora: {
      data: "2024-02-06",
      horaDe: "15:00",
      horaAte: "18:00",
    },
    ativo: true,
  },
  {
    numero: 35,
    cliente: "Construtora Planalto",
    tecnico: "Carlos Mendes",
    dataHora: {
      data: "2024-02-07",
      horaDe: "08:30",
      horaAte: "11:30",
    },
    ativo: false,
  },
  {
    numero: 36,
    cliente: "Móveis Design",
    tecnico: "João Silva",
    dataHora: {
      data: "2024-02-07",
      horaDe: "14:00",
      horaAte: "17:00",
    },
    ativo: true,
  },
  {
    numero: 37,
    cliente: "Eletrônicos Tech",
    tecnico: "Maria Santos",
    dataHora: {
      data: "2024-02-08",
      horaDe: "09:00",
      horaAte: "12:00",
    },
    ativo: true,
  },
  {
    numero: 38,
    cliente: "Borracharia Pneus",
    tecnico: "Pedro Oliveira",
    dataHora: {
      data: "2024-02-08",
      horaDe: "13:30",
      horaAte: "16:30",
    },
    ativo: true,
  },
  {
    numero: 39,
    cliente: "Floricultura Natureza",
    tecnico: "Ana Costa",
    dataHora: {
      data: "2024-02-09",
      horaDe: "10:00",
      horaAte: "12:00",
    },
    ativo: false,
  },
  {
    numero: 40,
    cliente: "Seguros Proteção",
    tecnico: "Carlos Mendes",
    dataHora: {
      data: "2024-02-09",
      horaDe: "14:00",
      horaAte: "16:00",
    },
    ativo: true,
  },
  {
    numero: 41,
    cliente: "Advocacia Legal",
    tecnico: "João Silva",
    dataHora: {
      data: "2024-02-12",
      horaDe: "08:00",
      horaAte: "10:00",
    },
    ativo: true,
  },
  {
    numero: 42,
    cliente: "Contabilidade Exact",
    tecnico: "Maria Santos",
    dataHora: {
      data: "2024-02-12",
      horaDe: "11:00",
      horaAte: "13:00",
    },
    ativo: true,
  },
  {
    numero: 43,
    cliente: "Telecomunicações Net",
    tecnico: "Pedro Oliveira",
    dataHora: {
      data: "2024-02-13",
      horaDe: "15:00",
      horaAte: "18:00",
    },
    ativo: false,
  },
  {
    numero: 44,
    cliente: "Transporte Cargas",
    tecnico: "Ana Costa",
    dataHora: {
      data: "2024-02-13",
      horaDe: "09:30",
      horaAte: "12:30",
    },
    ativo: true,
  },
  {
    numero: 45,
    cliente: "Metalúrgica Aço",
    tecnico: "Carlos Mendes",
    dataHora: {
      data: "2024-02-14",
      horaDe: "13:00",
      horaAte: "16:00",
    },
    ativo: true,
  },
  {
    numero: 46,
    cliente: "Grávida Moda",
    tecnico: "João Silva",
    dataHora: {
      data: "2024-02-14",
      horaDe: "10:00",
      horaAte: "12:00",
    },
    ativo: true,
  },
  {
    numero: 47,
    cliente: "Perfumaria Aroma",
    tecnico: "Maria Santos",
    dataHora: {
      data: "2024-02-15",
      horaDe: "14:30",
      horaAte: "17:30",
    },
    ativo: false,
  },
  {
    numero: 48,
    cliente: "Esportes Ativo",
    tecnico: "Pedro Oliveira",
    dataHora: {
      data: "2024-02-15",
      horaDe: "08:00",
      horaAte: "11:00",
    },
    ativo: true,
  },
  {
    numero: 49,
    cliente: "Bebidas Refresco",
    tecnico: "Ana Costa",
    dataHora: {
      data: "2024-02-16",
      horaDe: "12:00",
      horaAte: "15:00",
    },
    ativo: true,
  },
  {
    numero: 50,
    cliente: "Utilidades Casa",
    tecnico: "Carlos Mendes",
    dataHora: {
      data: "2024-02-16",
      horaDe: "16:00",
      horaAte: "18:00",
    },
    ativo: true,
  },
];
