import { RelatorioProdutividade } from "./types";

export const mockRelatoriosProdutividade: RelatorioProdutividade[] = [
  {
    id: 1,
    tecnico: "João Silva",
    horasTrabalhadas: "08:00",
    visitasAgendadas: 12,
    osRealizadas: 10,
    osNaoRealizadas: 2,
    visitasPendentes: 3,
  },
  {
    id: 2,
    tecnico: "Maria Santos",
    horasTrabalhadas: "07:30",
    visitasAgendadas: 15,
    osRealizadas: 14,
    osNaoRealizadas: 1,
    visitasPendentes: 2,
  },
  {
    id: 3,
    tecnico: "Pedro Oliveira",
    horasTrabalhadas: "08:15",
    visitasAgendadas: 10,
    osRealizadas: 8,
    osNaoRealizadas: 2,
    visitasPendentes: 4,
  },
  {
    id: 4,
    tecnico: "Ana Costa",
    horasTrabalhadas: "06:45",
    visitasAgendadas: 8,
    osRealizadas: 7,
    osNaoRealizadas: 1,
    visitasPendentes: 1,
  },
  {
    id: 5,
    tecnico: "Carlos Lima",
    horasTrabalhadas: "09:00",
    visitasAgendadas: 18,
    osRealizadas: 16,
    osNaoRealizadas: 2,
    visitasPendentes: 5,
  },
  {
    id: 6,
    tecnico: "Fernanda Rocha",
    horasTrabalhadas: "07:00",
    visitasAgendadas: 11,
    osRealizadas: 9,
    osNaoRealizadas: 2,
    visitasPendentes: 3,
  },
  {
    id: 7,
    tecnico: "Ricardo Alves",
    horasTrabalhadas: "08:30",
    visitasAgendadas: 14,
    osRealizadas: 12,
    osNaoRealizadas: 2,
    visitasPendentes: 4,
  },
  {
    id: 8,
    tecnico: "Juliana Pereira",
    horasTrabalhadas: "07:45",
    visitasAgendadas: 13,
    osRealizadas: 11,
    osNaoRealizadas: 2,
    visitasPendentes: 2,
  },
  {
    id: 9,
    tecnico: "Roberto Nunes",
    horasTrabalhadas: "08:20",
    visitasAgendadas: 16,
    osRealizadas: 15,
    osNaoRealizadas: 1,
    visitasPendentes: 6,
  },
  {
    id: 10,
    tecnico: "Amanda Souza",
    horasTrabalhadas: "06:30",
    visitasAgendadas: 9,
    osRealizadas: 8,
    osNaoRealizadas: 1,
    visitasPendentes: 2,
  },
  {
    id: 11,
    tecnico: "Lucas Mendes",
    horasTrabalhadas: "08:10",
    visitasAgendadas: 17,
    osRealizadas: 14,
    osNaoRealizadas: 3,
    visitasPendentes: 7,
  },
  {
    id: 12,
    tecnico: "Patrícia Gomes",
    horasTrabalhadas: "07:20",
    visitasAgendadas: 12,
    osRealizadas: 10,
    osNaoRealizadas: 2,
    visitasPendentes: 3,
  },
  {
    id: 13,
    tecnico: "Marcos Torres",
    horasTrabalhadas: "09:15",
    visitasAgendadas: 20,
    osRealizadas: 18,
    osNaoRealizadas: 2,
    visitasPendentes: 8,
  },
  {
    id: 14,
    tecnico: "Cristina Dias",
    horasTrabalhadas: "07:50",
    visitasAgendadas: 14,
    osRealizadas: 13,
    osNaoRealizadas: 1,
    visitasPendentes: 4,
  },
  {
    id: 15,
    tecnico: "Fábio Castro",
    horasTrabalhadas: "08:05",
    visitasAgendadas: 11,
    osRealizadas: 9,
    osNaoRealizadas: 2,
    visitasPendentes: 2,
  },
  {
    id: 16,
    tecnico: "Vanessa Lima",
    horasTrabalhadas: "06:40",
    visitasAgendadas: 10,
    osRealizadas: 8,
    osNaoRealizadas: 2,
    visitasPendentes: 3,
  },
  {
    id: 17,
    tecnico: "Diego Santos",
    horasTrabalhadas: "08:25",
    visitasAgendadas: 15,
    osRealizadas: 12,
    osNaoRealizadas: 3,
    visitasPendentes: 5,
  },
  {
    id: 18,
    tecnico: "Tatiane Almeida",
    horasTrabalhadas: "07:35",
    visitasAgendadas: 13,
    osRealizadas: 11,
    osNaoRealizadas: 2,
    visitasPendentes: 3,
  },
  {
    id: 19,
    tecnico: "Rafael Carvalho",
    horasTrabalhadas: "08:50",
    visitasAgendadas: 19,
    osRealizadas: 17,
    osNaoRealizadas: 2,
    visitasPendentes: 7,
  },
  {
    id: 20,
    tecnico: "Simone Ribeiro",
    horasTrabalhadas: "07:15",
    visitasAgendadas: 12,
    osRealizadas: 10,
    osNaoRealizadas: 2,
    visitasPendentes: 4,
  },
  {
    id: 21,
    tecnico: "Bruno Ferreira",
    horasTrabalhadas: "08:40",
    visitasAgendadas: 16,
    osRealizadas: 14,
    osNaoRealizadas: 2,
    visitasPendentes: 6,
  },
  {
    id: 22,
    tecnico: "Larissa Martins",
    horasTrabalhadas: "07:05",
    visitasAgendadas: 11,
    osRealizadas: 9,
    osNaoRealizadas: 2,
    visitasPendentes: 2,
  },
  {
    id: 23,
    tecnico: "Anderson Costa",
    horasTrabalhadas: "09:05",
    visitasAgendadas: 18,
    osRealizadas: 16,
    osNaoRealizadas: 2,
    visitasPendentes: 8,
  },
  {
    id: 24,
    tecnico: "Daniela Silva",
    horasTrabalhadas: "07:25",
    visitasAgendadas: 14,
    osRealizadas: 12,
    osNaoRealizadas: 2,
    visitasPendentes: 4,
  },
  {
    id: 25,
    tecnico: "Eduardo Rocha",
    horasTrabalhadas: "08:15",
    visitasAgendadas: 15,
    osRealizadas: 13,
    osNaoRealizadas: 2,
    visitasPendentes: 5,
  },
  {
    id: 26,
    tecnico: "Gabriela Nunes",
    horasTrabalhadas: "06:50",
    visitasAgendadas: 10,
    osRealizadas: 8,
    osNaoRealizadas: 2,
    visitasPendentes: 3,
  },
  {
    id: 27,
    tecnico: "Hugo Alves",
    horasTrabalhadas: "08:30",
    visitasAgendadas: 17,
    osRealizadas: 15,
    osNaoRealizadas: 2,
    visitasPendentes: 6,
  },
  {
    id: 28,
    tecnico: "Isabela Souza",
    horasTrabalhadas: "07:40",
    visitasAgendadas: 13,
    osRealizadas: 11,
    osNaoRealizadas: 2,
    visitasPendentes: 3,
  },
  {
    id: 29,
    tecnico: "Jorge Mendes",
    horasTrabalhadas: "08:55",
    visitasAgendadas: 20,
    osRealizadas: 18,
    osNaoRealizadas: 2,
    visitasPendentes: 9,
  },
  {
    id: 30,
    tecnico: "Karina Gomes",
    horasTrabalhadas: "07:10",
    visitasAgendadas: 12,
    osRealizadas: 10,
    osNaoRealizadas: 2,
    visitasPendentes: 4,
  },
  {
    id: 31,
    tecnico: "Leandro Torres",
    horasTrabalhadas: "08:20",
    visitasAgendadas: 16,
    osRealizadas: 14,
    osNaoRealizadas: 2,
    visitasPendentes: 5,
  },
  {
    id: 32,
    tecnico: "Mariana Dias",
    horasTrabalhadas: "06:45",
    visitasAgendadas: 11,
    osRealizadas: 9,
    osNaoRealizadas: 2,
    visitasPendentes: 2,
  },
  {
    id: 33,
    tecnico: "Nicolas Castro",
    horasTrabalhadas: "09:10",
    visitasAgendadas: 19,
    osRealizadas: 17,
    osNaoRealizadas: 2,
    visitasPendentes: 7,
  },
  {
    id: 34,
    tecnico: "Olivia Lima",
    horasTrabalhadas: "07:30",
    visitasAgendadas: 14,
    osRealizadas: 12,
    osNaoRealizadas: 2,
    visitasPendentes: 4,
  },
  {
    id: 35,
    tecnico: "Paulo Santos",
    horasTrabalhadas: "08:05",
    visitasAgendadas: 15,
    osRealizadas: 13,
    osNaoRealizadas: 2,
    visitasPendentes: 5,
  },
  {
    id: 36,
    tecnico: "Quezia Almeida",
    horasTrabalhadas: "07:50",
    visitasAgendadas: 13,
    osRealizadas: 11,
    osNaoRealizadas: 2,
    visitasPendentes: 3,
  },
  {
    id: 37,
    tecnico: "Renato Carvalho",
    horasTrabalhadas: "08:45",
    visitasAgendadas: 18,
    osRealizadas: 16,
    osNaoRealizadas: 2,
    visitasPendentes: 6,
  },
  {
    id: 38,
    tecnico: "Sabrina Ribeiro",
    horasTrabalhadas: "07:20",
    visitasAgendadas: 12,
    osRealizadas: 10,
    osNaoRealizadas: 2,
    visitasPendentes: 4,
  },
  {
    id: 39,
    tecnico: "Thiago Ferreira",
    horasTrabalhadas: "08:35",
    visitasAgendadas: 17,
    osRealizadas: 15,
    osNaoRealizadas: 2,
    visitasPendentes: 7,
  },
  {
    id: 40,
    tecnico: "Ursula Martins",
    horasTrabalhadas: "06:35",
    visitasAgendadas: 10,
    osRealizadas: 8,
    osNaoRealizadas: 2,
    visitasPendentes: 2,
  },
  {
    id: 41,
    tecnico: "Vitor Costa",
    horasTrabalhadas: "09:00",
    visitasAgendadas: 20,
    osRealizadas: 18,
    osNaoRealizadas: 2,
    visitasPendentes: 8,
  },
  {
    id: 42,
    tecnico: "Wanessa Silva",
    horasTrabalhadas: "07:45",
    visitasAgendadas: 14,
    osRealizadas: 12,
    osNaoRealizadas: 2,
    visitasPendentes: 4,
  },
  {
    id: 43,
    tecnico: "Xavier Rocha",
    horasTrabalhadas: "08:10",
    visitasAgendadas: 16,
    osRealizadas: 14,
    osNaoRealizadas: 2,
    visitasPendentes: 5,
  },
  {
    id: 44,
    tecnico: "Yasmin Nunes",
    horasTrabalhadas: "07:00",
    visitasAgendadas: 11,
    osRealizadas: 9,
    osNaoRealizadas: 2,
    visitasPendentes: 3,
  },
  {
    id: 45,
    tecnico: "Zé Alves",
    horasTrabalhadas: "08:25",
    visitasAgendadas: 17,
    osRealizadas: 15,
    osNaoRealizadas: 2,
    visitasPendentes: 6,
  },
  {
    id: 46,
    tecnico: "Alice Souza",
    horasTrabalhadas: "07:35",
    visitasAgendadas: 13,
    osRealizadas: 11,
    osNaoRealizadas: 2,
    visitasPendentes: 3,
  },
  {
    id: 47,
    tecnico: "Bruno Mendes",
    horasTrabalhadas: "08:50",
    visitasAgendadas: 19,
    osRealizadas: 17,
    osNaoRealizadas: 2,
    visitasPendentes: 7,
  },
  {
    id: 48,
    tecnico: "Carla Gomes",
    horasTrabalhadas: "07:15",
    visitasAgendadas: 12,
    osRealizadas: 10,
    osNaoRealizadas: 2,
    visitasPendentes: 4,
  },
  {
    id: 49,
    tecnico: "Daniel Torres",
    horasTrabalhadas: "08:40",
    visitasAgendadas: 16,
    osRealizadas: 14,
    osNaoRealizadas: 2,
    visitasPendentes: 5,
  },
  {
    id: 50,
    tecnico: "Elaine Dias",
    horasTrabalhadas: "06:55",
    visitasAgendadas: 11,
    osRealizadas: 9,
    osNaoRealizadas: 2,
    visitasPendentes: 2,
  },
];
